# Generated by Django 6.0.1 on 2026-03-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin_user',
            field=models.BooleanField(default=False),
        ),
    ]
