# Generated by Django 6.0.3 on 2026-03-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_groups_and_more'),
        ('admin', '0004_alter_logentry_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
