from .auth_views import *
from .dashboard_views import *
from .user_views import *
from .category_views import *
from .products_views import *
from .variants_views import *
from .ordermangement_views import *
from .returns_views import *
from .coupons_management import *
from .offermanagement_views import *
from .salesreport_views import *
from .banner_views import *