# Generated by Django 6.0.3 on 2026-04-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_alter_variants_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
