# Generated by Django 6.0.3 on 2026-04-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_alter_variants_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
