# Generated by Django 6.0.3 on 2026-04-22 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_alter_products_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantimage',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='adminpanel.category'),
        ),
    ]
