# Generated by Django 6.0.3 on 2026-04-23 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_alter_variantimage_options_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
