# Generated by Django 6.0.3 on 2026-04-23 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_alter_variants_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='uuid',
        ),
        migrations.AddField(
            model_name='products',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
