# Generated by Django 6.0.3 on 2026-04-23 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_remove_variants_uuid_products_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
