# Generated by Django 6.0.3 on 2026-05-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_returnrequest_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
