# Generated by Django 6.0.3 on 2026-05-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aichatmessage',
            new_name='ai_chat_aic_user_id_b43b46_idx',
            old_name='ai_chat_aic_user_id_92b937_idx',
        ),
    ]
